# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: vtgateservice.proto for package 'vtgateservice'

require 'grpc'
require 'proto/vtgateservice'

module Vtgateservice
  module Vitess

    # TODO: add proto service documentation here
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'vtgateservice.Vitess'

      rpc :Execute, Vtgate::ExecuteRequest, Vtgate::ExecuteResponse
      rpc :ExecuteShards, Vtgate::ExecuteShardsRequest, Vtgate::ExecuteShardsResponse
      rpc :ExecuteKeyspaceIds, Vtgate::ExecuteKeyspaceIdsRequest, Vtgate::ExecuteKeyspaceIdsResponse
      rpc :ExecuteKeyRanges, Vtgate::ExecuteKeyRangesRequest, Vtgate::ExecuteKeyRangesResponse
      rpc :ExecuteEntityIds, Vtgate::ExecuteEntityIdsRequest, Vtgate::ExecuteEntityIdsResponse
      rpc :ExecuteBatchShards, Vtgate::ExecuteBatchShardsRequest, Vtgate::ExecuteBatchShardsResponse
      rpc :ExecuteBatchKeyspaceIds, Vtgate::ExecuteBatchKeyspaceIdsRequest, Vtgate::ExecuteBatchKeyspaceIdsResponse
      rpc :StreamExecute, Vtgate::StreamExecuteRequest, stream(Vtgate::StreamExecuteResponse)
      rpc :StreamExecuteShards, Vtgate::StreamExecuteShardsRequest, stream(Vtgate::StreamExecuteShardsResponse)
      rpc :StreamExecuteKeyspaceIds, Vtgate::StreamExecuteKeyspaceIdsRequest, stream(Vtgate::StreamExecuteKeyspaceIdsResponse)
      rpc :StreamExecuteKeyRanges, Vtgate::StreamExecuteKeyRangesRequest, stream(Vtgate::StreamExecuteKeyRangesResponse)
      rpc :Begin, Vtgate::BeginRequest, Vtgate::BeginResponse
      rpc :Commit, Vtgate::CommitRequest, Vtgate::CommitResponse
      rpc :Rollback, Vtgate::RollbackRequest, Vtgate::RollbackResponse
      rpc :SplitQuery, Vtgate::SplitQueryRequest, Vtgate::SplitQueryResponse
      rpc :GetSrvKeyspace, Vtgate::GetSrvKeyspaceRequest, Vtgate::GetSrvKeyspaceResponse
    end

    Stub = Service.rpc_stub_class
  end
end
